name = "twoqueues-consumer"
main = "./src/index.ts"
compatibility_date = "2023-04-08"


[build]
command = "npm run build"
[build.upload]
format = "modules"

[[queues.consumers]]
  queue = "my-queue"
  max_batch_size = 10
  max_batch_timeout = 30
  max_retries = 10
  dead_letter_queue = "my-queue-dlq"